# =============================================================================
# TRADING MVP CONFIGURATION
# =============================================================================

initial_capital: 100000    # starting capital in USD

# Strategy Configuration
strategies:
  wheel: true             # enable Options Wheel strategy
  rotator: true           # enable Crypto Rotator strategy

# Capital Allocation (percentages must sum to 1.0)
allocation:
  wheel: 0.5              # 50% capital to wheel (if both enabled)
  rotator: 0.5            # 50% capital to rotator

# =============================================================================
# DATA SOURCE CONFIGURATION
# =============================================================================

# Data Mode: "live", "mock", or "hybrid"
data_mode: "live"

# Market Data Sources
data_sources:
  crypto:
    primary: "coingecko"         # Primary crypto data source
    symbols:                     # Mapping of strategy symbols to API identifiers
      BTC: "bitcoin"
      ETH: "ethereum"  
      SOL: "solana"
    rate_limit_per_minute: 10    # API calls per minute
    timeout_seconds: 30
    
  etf:
    primary: "yfinance"          # Primary ETF/stock data source
    secondary: "alpha_vantage"   # Backup source (requires API key)
    symbols:                     # Direct symbol mapping for ETFs
      SPY: "SPY"
      QQQ: "QQQ"
      IWM: "IWM"
    rate_limit_per_minute: 5
    timeout_seconds: 30

# API Fallback Strategy
fallback_strategy:
  on_api_failure: "use_cached"   # "use_cached", "use_mock", "fail"
  cache_expiry_minutes: 60
  enable_mock_fallback: true     # Use mock data if all APIs fail

# Market Data Settings
market_data:
  default_lookback_days: 7       # Default historical data period
  price_type: "close"            # "close", "adjusted_close", "average"
  currency: "USD"
  include_weekend_data: false    # Filter out weekend crypto data
  timezone: "America/New_York"   # Market timezone

# =============================================================================
# STRATEGY SYMBOL CONFIGURATION
# =============================================================================

# Options Wheel Strategy Assets
wheel_symbols: ["SPY", "QQQ", "IWM"]   # ETF tickers for wheel strategy

# Crypto Rotator Strategy Assets  
rotator_symbols: ["BTC", "ETH", "SOL"] # Crypto symbols for rotator strategy

# =============================================================================
# BACKTESTING SETTINGS
# =============================================================================

# Backtesting Parameters
backtesting:
  # Date Range Configuration
  start_date: "2024-01-01"       # Start date for historical backtesting (YYYY-MM-DD)
  end_date: "2024-12-31"         # End date for historical backtesting (YYYY-MM-DD)
  
  # Legacy simulation mode (when using mock data)
  weeks_to_simulate: 8           # Number of weeks for simulation mode
  enable_deterministic_mode: true # Use deterministic test data when data_mode="mock"
  
  # Backtesting Configuration
  rebalance_frequency: "weekly"  # "daily", "weekly", "monthly"
  initial_capital: 100000        # Starting capital (can override initial_capital)
  benchmark_symbol: "SPY"        # Benchmark for comparison
  
  # Performance Analysis
  risk_free_rate: 0.045          # Risk-free rate for Sharpe ratio calculation (4.5%)
  calculate_metrics: true        # Calculate advanced performance metrics
  
  # Transaction Costs (for realistic backtesting)
  commission_per_trade: 0.0      # Commission per trade ($0 for many brokers now)
  spread_bp: 2                   # Bid-ask spread in basis points (0.02%)
  slippage_bp: 1                 # Market impact slippage in basis points (0.01%)
  
# =============================================================================
# STRATEGY-SPECIFIC CONFIGURATION
# =============================================================================

# Options Wheel Strategy Parameters
wheel_strategy:
  put_strike_pct: 0.95           # Strike price as % of current price for cash-secured puts (95% = 5% OTM)
  call_strike_pct: 1.05          # Strike price as % of current price for covered calls (105% = 5% OTM)
  put_premium_pct: 0.02          # Premium as % of strike price for puts (2%)
  call_premium_pct: 0.015        # Premium as % of strike price for calls (1.5%)
  max_positions_per_symbol: 1    # Maximum concurrent positions per symbol
  
# Crypto Rotator Strategy Parameters  
rotator_strategy:
  lookback_weeks: 1              # Number of weeks to look back for performance
  rotation_frequency: "weekly"   # How often to evaluate rotation ("daily", "weekly", "monthly")
  min_holding_period: 7          # Minimum days before allowing rotation
  performance_metric: "return"   # Metric to use for rotation ("return", "sharpe", "momentum")

# Risk Management (future enhancement)
risk_management:
  max_position_size: 0.5         # Maximum position size as % of total capital
  enable_stop_losses: false      # Enable stop-loss orders
  max_daily_trades: 10           # Maximum trades per day